"""empty message

Revision ID: 077058d38320
Revises: c4b26f850593
Create Date: 2017-02-14 21:21:48.828812

"""

# revision identifiers, used by Alembic.
revision = '077058d38320'
down_revision = 'c4b26f850593'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bugs', 'bug_status', ['status'], ['status'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    # ### end Alembic commands ###
