"""empty message

Revision ID: 310453e642ca
Revises: d00c0deaf72d
Create Date: 2017-02-08 20:44:31.326920

"""

# revision identifiers, used by Alembic.
revision = '310453e642ca'
down_revision = 'd00c0deaf72d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('path', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'path')
    # ### end Alembic commands ###
