"""empty message

Revision ID: c4b26f850593
Revises: 089ea572a0da
Create Date: 2017-02-14 20:58:44.599471

"""

# revision identifiers, used by Alembic.
revision = 'c4b26f850593'
down_revision = '089ea572a0da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('hourly_rate', sa.NUMERIC(precision=9, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'hourly_rate')
    # ### end Alembic commands ###
