"""init db

Revision ID: d0c5dbdb361d
Revises: None
Create Date: 2017-01-28 17:37:13.402769

"""

# revision identifiers, used by Alembic.
revision = 'd0c5dbdb361d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dept', sa.CHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('emp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'department_pkey')
    )
    # ### end Alembic commands ###
